#!/bin/bash
# Process to enable smart widgets native with Ilm using slow models
# This script configures the environment for smart widgets with Ilm support

set -e

echo "🚀 Enabling Smart Widgets Native with Ilm (Slow Models)"
echo "========================================================"

# Configuration directory
CONFIG_DIR=".cursor"
CONFIG_FILE="${CONFIG_DIR}/smart-widgets-config.json"

# Create .cursor directory if it doesn't exist
if [ ! -d "$CONFIG_DIR" ]; then
    echo "📁 Creating .cursor directory..."
    mkdir -p "$CONFIG_DIR"
fi

# Check if config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Configuration file not found: $CONFIG_FILE"
    echo "Please ensure the configuration file exists."
    exit 1
fi

echo "✅ Configuration file found: $CONFIG_FILE"

# Validate JSON configuration
if command -v python3 &> /dev/null; then
    echo "🔍 Validating configuration..."
    python3 -m json.tool "$CONFIG_FILE" > /dev/null
    if [ $? -eq 0 ]; then
        echo "✅ Configuration is valid JSON"
    else
        echo "❌ Invalid JSON configuration"
        exit 1
    fi
fi

# Set environment variables for Ilm
export SMART_WIDGETS_ENABLED=true
export SMART_WIDGETS_NATIVE=true
export ILM_ENABLED=true
export ILM_AVAILABLE=true
export ILM_MODEL_TYPE=slow
export ILM_USE_SLOW_MODELS=true
export ILM_COST_OPTIMIZED=true

echo ""
echo "📋 Configuration Summary:"
echo "  - Smart Widgets: Enabled (Native)"
echo "  - Ilm: Available"
echo "  - Model Type: Slow"
echo "  - Cost Optimized: Yes"
echo ""

# Create environment file for persistence
ENV_FILE="${CONFIG_DIR}/smart-widgets.env"
cat > "$ENV_FILE" << EOF
# Smart Widgets Configuration
# Generated by enable-smart-widgets-ilm.sh
SMART_WIDGETS_ENABLED=true
SMART_WIDGETS_NATIVE=true
ILM_ENABLED=true
ILM_AVAILABLE=true
ILM_MODEL_TYPE=slow
ILM_USE_SLOW_MODELS=true
ILM_COST_OPTIMIZED=true
EOF

echo "💾 Environment variables saved to: $ENV_FILE"
echo ""
echo "✨ Smart Widgets Native with Ilm (Slow Models) is now enabled!"
echo ""
echo "To use these settings in your shell, run:"
echo "  source $ENV_FILE"
echo ""
